server:
  port: 8823

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml



#日志
logging:
  level:
    com.shop.city : debug
    springfox.documentation.spring.web.readers: error

#数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: qianhua
    password: guoqianhua

  # 单张照片的最大尺寸
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
#      enabled: false

  profiles:
    active: dev

#上传图片
imagepath:
  savePath: E:\image\qianhua
  visitPath: file:\\E:\image\qianhua


#自定义属性值
mylist:
  list1: 1,2,3,4,5




